--- 
# kindle mobi document genelater
#
#
# //*[@id="root"]/div/nav
#  #root > div > nav
#
#  //*[@id="root"]/div/div[2]/nav
#  #root > div > div.container.site__content > nav
#
#  //*[@id="root"]/div/div[2]/nav/div/div[5]/a
#  #root > div > div.container.site__content > nav > div > div:nth-child(5) > a
#  
#  <a class="sidebar-item__title" href="/concepts/output/">Output</a>
#
top_dir: content
recipe_slug: webpack

base_url: https://webpack.js.org/
index_url: https://webpack.js.org/concepts/
kindle_css: css/kindle.css
images_include: false

extract_sections:
   select_class:  .sidebar-item
   select_method: regex
   select_section_regex: "\\/$"
   select_article_regex: ".+#.+"     

#
kindlegen:
  compress:  0     # 0/1/2
  verbose:   true  # booleran
  locale:    en
  output_path:    /tmp/mobi




