--- 
# kindle mobi document genelater
#
#
top_dir: content
recipe_slug: unix

base_url: http://www.faqs.org/docs/artu/
index_url:  http://www.faqs.org/docs/artu/index.html
kindle_css: css/kindle.css
images_include: true

extract_sections:
   select_class:  .toc
   select_method: regex
   select_section_regex: "(preface|chapter)\\.html"
   select_article_regex: "html$"

#
kindlegen:
  compress:  0     # 0/1/2
  verbose:   true  # booleran
  locale:    en
  output_path:    /tmp/mobi


