--- 
# kindle mobi document genelater
#
#
top_dir: content
recipe_slug: svn

base_url: http://svnbook.red-bean.com/en/1.7/
index_url: http://svnbook.red-bean.com/en/1.7/index.html
kindle_css: css/kindle.css
images_include: true

extract_sections:
   select_class:  .toc
   select_method: regex
   select_section_regex: "svn\\.[a-z]+\\.html"
   select_article_regex: "html$"

#
kindlegen:
  compress:  0     # 0/1/2
  verbose:   true  # booleran
  locale:    en
  output_path:    /tmp/mobi



