--- 
# kindle mobi document genelater
#
#
top_dir: content
recipe_slug: svn2
base_url: http://svnbook.red-bean.com/en/1.7/
index_url: http://svnbook.red-bean.com/en/1.7/index.html
kindle_css: css/kindle.css

#
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds: 
   - huey
   - dewey
   - louie
   - fred
xmas-fifth-day: 
   calling-birds: four
   french-hens: 3
   golden-rings: 5
   partridges: 
     count: 1
     location: "a pear tree"
   turtle-doves: two



